### ISSUE TITLE
Unnable to create session file after closing connections

### ISSUE THREAD

**Issue by miguelbcr** [VictorAlbertos/RxSocialConnect-Android#19]
I get this error when I try to login after calling `RxSocialConnect.closeConnections()`  :

java.io.FileNotFoundException: /data/user/0/com.my.app/files/RxSocialConnect/FacebookApi: open failed: ENOENT (No such file or directory) on [Disk.java](https://github.com/VictorAlbertos/RxSocialConnect-Android/blob/2.x/core/src/main/java/org/fuckboilerplate/rx_social_connect/internal/persistence/Disk.java#L48)

I've been debuging and these are my conclusions;

- The first time the app is launched and `RxSocialConnect.register()` the `cacheDirectory` is created, so the session file (FacebookApi) in this case is created.
- But if I do logout in my app and I call to `RxSocialConnect.closeConnections()` the `cacheDirectory`  is deleted, so if I try login again  the `cacheDirectory` is not created because `RxSocialConnect.register()`  is not called anymore unless I destroy the app and launch it again.

So, as a possible solution, you could call `cacheDirectory.mkdirs();` before [the file creation](https://github.com/VictorAlbertos/RxSocialConnect-Android/blob/2.x/core/src/main/java/org/fuckboilerplate/rx_social_connect/internal/persistence/Disk.java#L48)

What do you think?
Thanks!

**Comment by VictorAlbertos** [comment]
Thanks @miguelbcr ;)

Your solution sounds good to me. I'll try to fix it this weekend, but a PR is also welcome :P

**Comment by miguelbcr** [comment]
Hi @VictorAlbertos ,
I've been debuging again and the error is not related with your lib, sorry, my app deletes all files under `files ` private dir at the same time `RxSocialConnect.closeConnections()`is called in order to delete all files related with the current user session. 

Anyway it would be good to add `cacheDirectory.mkdirs();` in order to ensure that  `RxSocialConnect` folder exists before creating the file as a defensive technique. If not, I could force to create `RxSocialConnect` folder.

Thanks!
