### ISSUE TITLE
What Encryption key  we have to use ?

### ISSUE THREAD

**Issue by ArisChoice** [VictorAlbertos/RxSocialConnect-Android#20]
for this 
     RxSocialConnect.register(this, "myEncryptionKey")
            .using(new GsonSpeaker());

**Comment by VictorAlbertos** [comment]
You just need to supply a random string, whatever you want. Just be aware that once the encryption key has been set, you can't change it anymore.

**Comment by ArisChoice** [comment]
fine thanks,
Can you tell me  how to use social contacts api 's,Or Please provide a code sample for social contact api's.
Twitter,google,facebook.

**Comment by VictorAlbertos** [comment]
Take a look at the [REAMDE](https://github.com/VictorAlbertos/RxSocialConnect-Android). Everything it's there.
