### ISSUE TITLE
Activity Connect bug

### ISSUE THREAD

**Issue by Cool04ek** [VictorAlbertos/RxSocialConnect-Android#21]
Hi, thank you for this awesome library. I found it very useful. However, I have encountered an unpleasant bug I would like to report. 
When you start ActivityConnect and then close it before webview has loaded you will get NPE in this line 
``
if (!url.startsWith(service.callbackUrl())) return super.shouldOverrideUrlLoading(view, url);
`` 
because activity is already closed and service is null. 
I can provide PR with fix as well.

**Comment by Cool04ek** [comment]
Here is PR with fix I assume can help - #22

**Comment by VictorAlbertos** [comment]
Closed by #22

**Comment by Cool04ek** [comment]
By the way, would you provide new version for the maven repo so I can you lib as gradle dependency?
