### ISSUE TITLE
Screen Orientation

### ISSUE THREAD

**Issue by Cool04ek** [VictorAlbertos/RxSocialConnect-Android#23]
Hi. I would like to request a feature, if it aint present in lib now.

Can I explicitly set up screen orientation for ActivityConnect? So it will be for example portrait all the time? 
If no, would you provide such in a future? I would be glad to help with PR.

**Comment by VictorAlbertos** [comment]
Why do you need this? 

A PR will be welcome, but you'll have to supply the same implementation for both branches, 1.x and 2.x.

**Comment by Cool04ek** [comment]
Basically, because of WebView. When you rotate screen, webview reloads and users progress is lost. I have all screens in app in portrait so I don't need this part to be able to rotate as well. This will help me to save users time if he rotates screen and loses all the data he had already typed.
